# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: signdemo.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'signdemo.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0esigndemo.proto\x12\x08signdemo\"1\n\x0bPingRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x11\n\ttimestamp\x18\x02 \x01(\x03\"6\n\tPingReply\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\x0f\n\x07service\x18\x02 \x01(\t\x12\x0c\n\x04time\x18\x03 \x01(\x03\x32>\n\x08SignDemo\x12\x32\n\x04Ping\x12\x15.signdemo.PingRequest\x1a\x13.signdemo.PingReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'signdemo_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PINGREQUEST']._serialized_start=28
  _globals['_PINGREQUEST']._serialized_end=77
  _globals['_PINGREPLY']._serialized_start=79
  _globals['_PINGREPLY']._serialized_end=133
  _globals['_SIGNDEMO']._serialized_start=135
  _globals['_SIGNDEMO']._serialized_end=197
# @@protoc_insertion_point(module_scope)
